### PR TITLE
Add metrics to monitor Redis connections

### PR DESCRIPTION
**Pull request by vivekkothari**
To Fix 
Metrics for Jedis Pool #21

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Awesome, thank you!

**Comment by vivekkothari** [comment]
can you release it to maven central?

**Comment by benjamin-bader** [comment]
Yes, but it will have to wait until later this week - I've switched machines since the last release, and need to re-discover some Maven incantations that will get it done.  For now though, it's bedtime here in California.

Thanks again for your contribution!

**Comment by benjamin-bader** [comment]
Version 0.9.1-1 has been pushed to Maven Central, and should be available within an hour or so.

**Comment by vivekkothari** [comment]
There seems to be something wrong with the artifact on Maven.
http://mvnrepository.com/artifact/com.bendb.dropwizard/dropwizard-redis/0.9.1-1
Also It does't have my changes. Can you please check?

**Comment by benjamin-bader** [comment]
I downloaded and decompiled the jar from the link you posted, and the extra metrics you added in this PR are definitely there.  Are you sure that you're pulling the new version into your project?

What other problem are you seeing?

**Pull request merged**
