### PR TITLE
Use configured timeout value as the time to wait for a connection from the pool.

### PR DESCRIPTION
**Pull request by vasukisesh**
This is a solution for Issue #52

### CODE REVIEW

**Comment by vasukisesh** [comment]
@benjamin-bader Can you assist with the Travis CI failure? Looks like maven resolution problem?

**Comment by benjamin-bader** [comment]
Thanks for the PR!

Ugh, yeah, the travis error looks like an oversight on my part the last time I bumped the versions.  I'll fix that.  Thanks!

**Comment by benjamin-bader** [comment]
@vasukisesh I just fixed the pom issue in master; you'll need to rebase your branch to get travis working again.  Thanks for bearing with me on this!

**Comment by vasukisesh** [comment]
@benjamin-bader Done, thank you!

**Comment by benjamin-bader** [comment]
Thanks for the contribution!  This ought to be available in a snapshot build soonish.  I've had no end of trouble using Maven to make a proper release, having tried several times over the past year.  It looks like switching this project to building with Gradle will help, so this fix won't see a stable release until that happens.

**Comment by vasukisesh** [comment]
@benjamin-bader Oh, that's too bad about the maven trouble. We use maven too, so we would certainly like it to be in a release build if possible. Anything I can assist with in making a release build?

**Comment by benjamin-bader** [comment]
Thanks for your kind offer.  The trouble is actually uploading artifacts to Sonatype; for some reason, it started taking ~30 minutes, and would not actually succeed.  I spent a good amount of time with their support staff, but to no avail.  I suspect that some bit of the publishing code we use has suffered some bitrot.

Since I don't use maven-the-cli-tool at all these days, I'm not inclined to invest a lot of time in maintaining a pom-based build.  I _do_ know Gradle pretty well, and haven't had similar issues with my gradle-based OSS projects, so this seems like the path of least resistance for me.

**Comment by benjamin-bader** [comment]
FWIW it shouldn't take long - today or tomorrow, maybe.

**Comment by benjamin-bader** [comment]
OK, got a build released - version 1.3.5-1 should be available in Maven Central within the next 15 minutes.

Dunno if you've used Gradle much, but tldr instead of `mvn verify` you can do `./gradlew check`.  If you want to only test one subproject, you spell it like `./gradlew :dropwizard-jooq:check`.

**Comment by vasukisesh** [comment]
Awesome, thank you!

**Pull request merged**
