### PR TITLE
Adds configuration option for SSL/TLS

### PR DESCRIPTION
**Pull request by haydentherapper**
Jedis 2.9.0 added support for SSL connections.

### CODE REVIEW

**Comment by benjamin-bader** [comment]
Thanks for the PR!  Everything basically looks great; the only question I have is whether, in `JedisFactory`, the body of `setUrl` will override the configured value of `ssl`; it looks possible to say `ssl = true` in the config file, but use a scheme of `redis://` and have the original config value be ignored.

I'm not sure if that matters, or if it's even possible.  Thoughts?

**Comment by haydentherapper** [comment]
If we didn't want to have this conflict, we could have `setUrl` ignore the scheme. Alternatively, SSL could be enabled only by using the `rediss://` scheme.
I'm leaning towards the first, and revert back to ignore the URI's scheme as before.

**Comment by haydentherapper** [comment]
I've updated the PR. If the scheme is `redis://`, then we do not override the boolean `ssl`.

**Comment by benjamin-bader** [comment]
Looks great - thanks for the contribution!

**Comment by haydentherapper** [comment]
Do you know when you can release to Maven?

**Comment by benjamin-bader** [comment]
Version 1.0.0-1 should be available in Maven Central around now.

**Pull request merged**
